version: 2
jobs:
  "golang-1.12":
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/go.mozilla.org/cose/
    environment:
      - GO111MODULE: "on" # yaml sees an unquoted on value as "true" but go checks for "on"
    steps:
      - checkout
      - run:
          name: install rust and cargo
          command: |
            sudo apt-get install libnss3-dev
            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
            source $HOME/.cargo/env
            echo $PATH
            which cargo
      - run:
          name: print rust and cargo version information
          command: |
            source $HOME/.cargo/env
            rustc --version
            cargo --version
      - run:
          name: run tests
          command: |
            source $HOME/.cargo/env
            make ci
  "golang-1.13":
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/go.mozilla.org/cose/
    environment:
      - GO111MODULE: "on" # yaml sees an unquoted on value as "true" but go checks for "on"
    steps:
      - checkout
      - run:
          name: install rust and cargo
          command: |
            sudo apt-get install libnss3-dev
            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
            source $HOME/.cargo/env
            echo $PATH
            which cargo
      - run:
          name: print rust and cargo version information
          command: |
            source $HOME/.cargo/env
            rustc --version
            cargo --version
      - run:
          name: run tests
          command: |
            source $HOME/.cargo/env
            make ci

workflows:
  version: 2
  build:
    jobs:
      - "golang-1.12"
      - "golang-1.13"
